services:
  - type: web
    name: cutout-studio
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 300 --bind 0.0.0.0:$PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CUDA_VISIBLE_DEVICES
        value: ""
      - key: ORT_LOGGING_LEVEL
        value: "3"
      - key: PYTHONUNBUFFERED
        value: "1"
